# Copy to streams.conf and fill in your camera URLs:
#   cp streams.conf.example streams.conf
#
# RTSPS example:
# STREAM_1="rtsps://username:password@camera1.example.com/stream1"

STREAM_1="rtsps://192.168.100.12:7441/XXXXXXX?enableSrtp"
STREAM_2="rtsps://192.168.100.12:7441/XXXXXXX?enableSrtp"
STREAM_3="rtsps://192.168.100.12:7441/XXXXXXX?enableSrtp"
STREAM_4="rtsps://192.168.100.12:7441/XXXXXXX?enableSrtp"

